name: Microservicio Productos CI/CD

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalación de dependencias
        run: npm ci

      - name: Build del servicio
        run: npm run build

      - name: Simulación de despliegue
        run: |
          echo "Iniciando despliegue simulado..."
          echo "Contenedor subido a Docker Hub simulado."
          echo "Despliegue en AWS ECS simulado completado con éxito."

  versioning-and-changelog:
    needs: build-and-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Incremento automático de versión y Changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-file: 'CHANGELOG.md'
